namespace Pancake.Tween
{
    public enum Ease
    {
        Linear = 0,
        InSine,
        OutSine,
        InOutSine,
        InQuad, // Accelerate
        OutQuad,
        InOutQuad,
        InCubic,
        OutCubic,
        InOutCubic,
        InQuart,
        OutQuart,
        InOutQuart,
        InQuint,
        OutQuint,
        InOutQuint,
        InExpo,
        OutExpo,
        InOutExpo,
        InCirc,
        OutCirc,
        InOutCirc,
        InBack,
        OutBack,
        InOutBack,
        InElastic,
        OutElastic,
        InOutElastic,
        InBounce,
        OutBounce,
        InOutBounce,
        Accelerate,
        Decelerate,
        AccelerateDecelerate,
        Anticipate,
        Overshoot,
        AnticipateOvershoot,
        Bounce,
        Parabolic,
        Sine,
        CustomCurve = -1
    }

    public enum EaseWithOutCurve
    {
        Linear = Ease.Linear,
        InSine = Ease.InSine,
        OutSine = Ease.OutSine,
        InOutSine = Ease.InOutSine,
        InQuad = Ease.InQuad, // Accelerate
        OutQuad = Ease.OutQuad,
        InOutQuad = Ease.InOutQuad,
        InCubic = Ease.InCubic,
        OutCubic = Ease.OutCubic,
        InOutCubic = Ease.InOutCubic,
        InQuart = Ease.InQuart,
        OutQuart = Ease.OutQuart,
        InOutQuart = Ease.InOutQuart,
        InQuint = Ease.InQuint,
        OutQuint = Ease.OutQuint,
        InOutQuint = Ease.InOutQuint,
        InExpo = Ease.InExpo,
        OutExpo = Ease.OutExpo,
        InOutExpo = Ease.InOutExpo,
        InCirc = Ease.InCirc,
        OutCirc = Ease.OutCirc,
        InOutCirc = Ease.InOutCirc,
        InBack = Ease.InBack,
        OutBack = Ease.OutBack,
        InOutBack = Ease.InOutBack,
        InElastic = Ease.InElastic,
        OutElastic = Ease.OutElastic,
        InOutElastic = Ease.InOutElastic,
        InBounce = Ease.InBounce,
        OutBounce = Ease.OutBounce,
        InOutBounce = Ease.InOutBounce,
        Accelerate = Ease.Accelerate,
        Decelerate = Ease.Decelerate,
        AccelerateDecelerate = Ease.AccelerateDecelerate,
        Anticipate = Ease.Anticipate,
        Overshoot = Ease.Overshoot,
        AnticipateOvershoot = Ease.AnticipateOvershoot,
        Bounce = Ease.Bounce,
        Parabolic = Ease.Parabolic,
        Sine = Ease.Sine,
    }
}